FROM node:14

LABEL author="hhh <haunghaohao86@gmail.com.com>"
LABEL describe="file_server"

RUN mkdir -p /home/file_server
WORKDIR /home/file_server

COPY package.json ./


COPY  . /home/file_server


RUN npm install

EXPOSE 8080

CMD npm i&&  npm run file